version: '3.8'

services:
  influxdb:
    image: influxdb:2
    container_name: influxdb
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=homelab
      - DOCKER_INFLUXDB_INIT_BUCKET=homelab
    ports:
      - 8086:8086
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2

  grafana:
    image: grafana/grafana:11.2.0-ubuntu
    container_name: grafana
    restart: always
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel, grafana-simple-json-datasource
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_PASSWORD}
    ports:
      - 3000:3000
    user: '1000:1000'
    volumes:
      - grafana-data:/var/lib/grafana
volumes:
  grafana-data:
  influxdb2-data:
  influxdb2-config:
